name: Continuous Deployment

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/rose

    steps:
      - name: Fetch and checkout latest tag
        uses: actions/checkout@v2
        run: |
          git fetch --prune --unshallow --tags 
          latesttag=$(git describe --tags)
          echo checking out ${latesttag}
          git checkout ${latesttag}

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Install production only dependencies
        run: npm ci --only=production
      
      - name: Restart server application
        run: pm2 restart rose